In [1]:
334+546

880

In [2]:
900-434

466

In [3]:
898/2

449.0

In [4]:
87*45

3915

In [5]:
print("Hello")

Hello


In [6]:
print("WELCOME to IT")

WELCOME to IT


In [8]:
print("\n")

# Heading 1

* point 1
* point 2

1. yess
2. noo


## heading2

#### foot

######## ghgh

In [10]:
print("hello\n world")

hello
 world


In [11]:
import os

In [12]:
os.getcwd()

'C:\\Users\\SS\\Training'

In [16]:
os.chdir('C:\\Users\\SS\\Training')

In [17]:
os.listdir('C:\\Users\\SS\\Training')

['.ipynb_checkpoints', 'Day 7.ipynb']

In [18]:
os.mkdir("Empty_folder")

In [19]:
os.rmdir("Empty_folder")

In [20]:
os.mkdir("New_by_me")

In [21]:
os.rmdir("New_by_me")

In [18]:
import random as r


In [2]:
val=r.random()
print(val)

0.5878311716742642


In [3]:
val=r.randint(1,10)
print(val)

8


In [4]:
m=['hi','amit','hello']
print(r.choice(m))

amit


In [5]:
print(r.choice(m))

hi


In [6]:
print(r.choices(m,k=3))

['hi', 'hello', 'hi']


In [7]:
print(r.shuffle(m))

None


In [8]:
print(r.shuffle(m))

None


In [9]:
val=r.shuffle(m)
print(val)

None


In [11]:
print(r.shuffle(m))

None


In [12]:
l=[2,45,67]
print(r.shuffle(l))

None


In [13]:
print(l)

[2, 67, 45]


In [14]:
print(r.choices(l,k=3))

[67, 45, 67]


In [16]:
print(l)

[45, 2, 67]


In [20]:
r.shuffle(l)

In [21]:
l

[2, 67, 45]

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,34,57],[78,4,9,76],[21,45,98,7]])
a

array([[ 1,  2, 34, 57],
       [78,  4,  9, 76],
       [21, 45, 98,  7]])

In [3]:
a.size

12

In [5]:
a.shape

(3, 4)

In [8]:
a[0][3]

57

In [10]:
a[2][:2]

array([21, 45])

In [12]:
a[2,[0,1]]

array([21, 45])

In [13]:
a[2,:2]

array([21, 45])

In [14]:
a[2,2:]

array([98,  7])

In [15]:
a[:,:]

array([[ 1,  2, 34, 57],
       [78,  4,  9, 76],
       [21, 45, 98,  7]])

In [18]:
print(a)

[[ 1  2 34 57]
 [78  4  9 76]
 [21 45 98  7]]


In [19]:
a[1:,2:]

array([[ 9, 76],
       [98,  7]])

In [20]:
a[:,3:]

array([[57],
       [76],
       [ 7]])

In [24]:
a[1,[0,1]] 

array([78,  4])

# arrange

In [27]:
list(range(4))

[0, 1, 2, 3]

In [28]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [31]:
np.arange(4.5,7.1,0.1)

array([4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7,
       5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. ])

In [32]:
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [33]:
np.arange(np.sqrt(25))

array([0., 1., 2., 3., 4.])

In [34]:
np.max(np.arange(10))

9

In [35]:
a.max()

98

In [36]:
a

array([[ 1,  2, 34, 57],
       [78,  4,  9, 76],
       [21, 45, 98,  7]])

In [38]:
a.min()

1

In [39]:
a.mean()

36.0

In [42]:
a.argmax()

10

In [43]:
a.argmin()

0

In [44]:
a.sort()

In [45]:
a

array([[ 1,  2, 34, 57],
       [ 4,  9, 76, 78],
       [ 7, 21, 45, 98]])

In [46]:
a+3

array([[  4,   5,  37,  60],
       [  7,  12,  79,  81],
       [ 10,  24,  48, 101]])

In [47]:
import random as r

In [48]:
np.random.rand(3,3)

array([[0.179392  , 0.51604451, 0.83400138],
       [0.70506342, 0.75127836, 0.8289787 ],
       [0.85701544, 0.25902927, 0.17455984]])

In [58]:
l=np.random.randint(9,90,12).reshape(6,2)

In [57]:
np.random.randn(3,4).reshape(2,6)

array([[-1.10242019,  0.14824169,  0.99854065,  1.3227321 , -0.50759418,
        -0.97204376],
       [ 0.69491844,  1.36935595,  0.82885805,  0.9172962 ,  1.43765715,
        -1.0271766 ]])

In [59]:
l.sum(axis=0)

array([460, 178])

In [60]:
l.sum()

638

In [61]:
l.sum(axis=1)

array([143,  98,  66, 109, 110, 112])

In [62]:
l

array([[86, 57],
       [82, 16],
       [56, 10],
       [74, 35],
       [74, 36],
       [88, 24]])

In [63]:
t=np.array([[[1,2],[2,3]],[[3,4],[4,5]]])

In [64]:
t

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]]])

In [66]:
t.shape

(2, 2, 2)

In [67]:
t.size

8

In [80]:
f=np.array([[[2,4,1],[1,3,2]],[[3,4,2],[1,2,2]],[[3,4,4],[1,2,4]],[[2,4,3],[1,3,2]]])

In [81]:
f

array([[[2, 4, 1],
        [1, 3, 2]],

       [[3, 4, 2],
        [1, 2, 2]],

       [[3, 4, 4],
        [1, 2, 4]],

       [[2, 4, 3],
        [1, 3, 2]]])

In [75]:
np.nan+45

nan

In [82]:
f.shape

(4, 2, 3)