In [1]:
import numpy as np

In [3]:
a=np.array([])
b=np.array([34,78,12])
c=np.array([[12,3,45],[87,65,4]])

In [14]:
a

array([], dtype=float64)

In [13]:
b

array([34, 78, 12])

In [12]:
c

array([[12,  3, 45],
       [87, 65,  4]])

In [11]:
a

array([], dtype=float64)

In [15]:
type(a)

numpy.ndarray

In [16]:
b+[23,45,67]

array([ 57, 123,  79])

In [17]:
type(c)

numpy.ndarray

In [18]:
b

array([34, 78, 12])

In [19]:
a.ndim

1

In [20]:
c.ndim

2

In [21]:
c.size

6

In [23]:
b.size

3

In [24]:
c.shape

(2, 3)

In [29]:
d=np.array([r.random(),r.random()])

In [26]:
import random as r

In [27]:
d=np.array([r.random(),r.random()])

In [28]:
d

array([0.25726312, 0.55120806])